### ISSUE TITLE
serialization of optional of enum fails

### ISSUE THREAD

**Issue by loyada** [loyada/typedpy#150]
>>> class Foo(ImmutableStructure):
    pref: Enum[BillPaymentMethod]
    
>>> class Foo2(ImmutableStructure):
    pref: NoneField | Enum[BillPaymentMethod]
    
>>>Serializer(Foo(pref="wire")).serialize()
{'pref': 'wire'}

>>>Serializer(Foo2(pref="wire")).serialize()
Traceback (most recent call last):
  File "/Users/dcanas/.pyenv/versions/3.9.6/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/dcanas/Library/Caches/pypoetry/virtualenvs/services-B_yEDTBn-py3.9/lib/python3.9/site-packages/typedpy/serialization_wrappers.py", line 178, in serialize
    return serialize(
  File "/Users/dcanas/Library/Caches/pypoetry/virtualenvs/services-B_yEDTBn-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 884, in serialize
    return serialize_internal(
  File "/Users/dcanas/Library/Caches/pypoetry/virtualenvs/services-B_yEDTBn-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 825, in serialize_internal
    result[mapped_key] = serialize_val(
  File "/Users/dcanas/Library/Caches/pypoetry/virtualenvs/services-B_yEDTBn-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 628, in serialize_val
    return serialize_multifield_wrapper(
  File "/Users/dcanas/Library/Caches/pypoetry/virtualenvs/services-B_yEDTBn-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 621, in serialize_multifield_wrapper
    raise ValueError(f"{name}: cannot serialize value: {val}")
ValueError: pref: cannot serialize value: wire

**Comment by loyada** [comment]
done
