### ISSUE TITLE
create-stubs-for-dir regression

### ISSUE THREAD

**Issue by loyada** [loyada/typedpy#223]
```
Traceback (most recent call last):
  File "/Users/dloya/Library/Caches/pypoetry/virtualenvs/services-A0NDnRDU-py3.9/bin/create-stubs-for-dir", line 8, in <module>
    sys.exit(main())
  File "/Users/dloya/Library/Caches/pypoetry/virtualenvs/services-A0NDnRDU-py3.9/lib/python3.9/site-packages/typedpy/scripts/create_stubs.py", line 14, in main
    input_dir = str(Path(args.directory).resolve())
AttributeError: 'Namespace' object has no attribute 'directory'

```

time to add tests for scripts ...

**Comment by loyada** [comment]
done in 2.18.4
