### ISSUE TITLE
error deserializing versioned structures

### ISSUE THREAD

**Issue by alex-vayu** [loyada/typedpy#97]
```python

from typedpy import ImmutableStructure, String, Versioned, Deleted, Deserializer


class FooBar(ImmutableStructure):
    data = String


class Foo(ImmutableStructure):
    data = String
    bar = FooBar


class VersionedFoo(Versioned):
    foo = Foo
    _versions_mapping = [
        {
            "foo._mapper": {
                "data": "string_data",
                "string_data": Deleted,
                "bar": "foobar",
                "foobar": Deleted,
                "bar._mapper": {
                    "data": "string_data",
                    "string_data": Deleted,

                }
            }
        }
    ]


v1 = {
    "version": 1,
    "foo": {
        "string_data": "Foo",
        "foobar": {
            "string_data": "FooBar"
        }
    }
}

v2 = {
    "version": 2,
    "foo": {
        "data": "Foo",
        "bar": {
            "data": "FooBar"
        }
    }
}

wrapped_v1: VersionedFoo = Deserializer(VersionedFoo).deserialize(v1)
wrapped_v2: VersionedFoo = Deserializer(VersionedFoo).deserialize(v2)

assert wrapped_v1.foo == wrapped_v2.foo

```

```
Traceback (most recent call last):
  File "/Users/alex.benenson/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch.py", line 51, in <module>
    wrapped_v1: VersionedFoo = Deserializer(VersionedFoo).deserialize(v1)
  File "/Users/alex.benenson/Library/Caches/pypoetry/virtualenvs/services-pHQVF7vU-py3.9/lib/python3.9/site-packages/typedpy/serialization_wrappers.py", line 76, in deserialize
    return deserialize_structure(
  File "/Users/alex.benenson/Library/Caches/pypoetry/virtualenvs/services-pHQVF7vU-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 575, in deserialize_structure
    return deserialize_structure_internal(
  File "/Users/alex.benenson/Library/Caches/pypoetry/virtualenvs/services-pHQVF7vU-py3.9/lib/python3.9/site-packages/typedpy/serialization.py", line 493, in deserialize_structure_internal
    input_dict = convert_dict(the_dict, versions_mapping)
  File "/Users/alex.benenson/Library/Caches/pypoetry/virtualenvs/services-pHQVF7vU-py3.9/lib/python3.9/site-packages/typedpy/versioned_mapping.py", line 57, in convert_dict
    mapped_dict = _convert(mapped_dict, mapping)
  File "/Users/alex.benenson/Library/Caches/pypoetry/virtualenvs/services-pHQVF7vU-py3.9/lib/python3.9/site-packages/typedpy/versioned_mapping.py", line 37, in _convert
    content = mapped_dict[field_name]
KeyError: 'foo._ma'

```

**Comment by loyada** [comment]
fixed in cf4f8093ceabb0b52c1872e4112fcb5d92ca3284
